import "./globals.css";
import Link from "next/link";
import { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";
export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorials-Codevolution",
    template: "%s | Codevolution",
    absolute: "",
  },

  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white min-h-screen flex flex-col">
        {/* <!-- Header --> */}
        <header className="flex  bg-blue-400 text-4xl h-24  rounded px-4 items-center  justify-around">
          <Link
            href="/"
            className="border rounded border-black text-white bg-blue-700 hover:bg-blue-900 px-2 py-1 left-2 top-2"
          >
            Home
          </Link>
          <h1 className="text-blue-700 bg-slate-800 text-6xl border-4 rounded border-black">
            Header
          </h1>
        </header>

        {/* <!-- Main Content --> */}
        <main className="  flex justify-center items-center flex-col mt-40 text-4xl">
          {/* <ErrorWrapper>{children}</ErrorWrapper> */}
          {children}
        </main>

        {/* <!-- Footer --> */}
        <footer className="bg-gray-600 bottom-0 w-full h-24 text-white text-3xl mt-auto rounded px-4 ">
          Footer
        </footer>
      </body>
    </html>
  );
}
