import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white min-h-screen flex flex-col">
        {/* <!-- Header --> */}
        <header className="flex  bg-blue-400 text-4xl h-24  rounded px-4 items-center justify-center">
          Header
        </header>

        {/* <!-- Main Content --> */}
        <main className=" flex justify-center items-center flex-col mt-40 text-4xl">
          {children}
        </main>

        {/* <!-- Footer --> */}
        <footer className="bg-gray-600 bottom-0 w-full h-24 text-white text-3xl mt-auto rounded px-4 ">
          Footer
        </footer>
      </body>
    </html>
  );
}
